### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by Wanted135** [Salty-Coder/Channel-Cleaner#1]
The provided token is not invalid, got it straight up from "Local Storage -> Token"

Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (C:\Users\xxxx\Downloads\Channel-Cleaner-main\node_modules\discord.js\src\client\Client.js:204:52)
    at Object.<anonymous> (C:\Users\xxxx\Downloads\Channel-Cleaner-main\index.js:111:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  [Symbol(code)]: 'TOKEN_INVALID'

**Comment by bns34** [comment]
The token you put in the program is invalid. Check it is the token for your bot and retry.

**Comment by Wanted135** [comment]
It's a valid token that I got from the "Application -> Local Storage -> https://discord.com -> token"

**Comment by Wanted135** [comment]
I added you on discord

**Comment by bns34** [comment]
The token is from the "bot" section of your application. You will see "TOKEN", click copy.

**Comment by Wanted135** [comment]
Worked thanks
